import "./globals.css"
import Header from "../Components/ui/Header";
import { CartProvider } from "@/Components/context/CartContext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <CartProvider>
           <Header/>
          {children}
        </CartProvider>
        </body>
    </html>
  );
}
