import "./globals.css"
import Header from "../Components/ui/Header";
import { CartProvider } from "@/Components/context/CartContext";
import { AuthProvider } from "@/Components/context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <AuthProvider>
          <CartProvider>
             <Header/>
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
